### ISSUE TITLE
Demo world doesn't load

### ISSUE THREAD

**Issue by Patil2099** [Jackrekirby/minecraft-ca-ts#1]
![image](https://github.com/Jackrekirby/minecraft-ca-ts/assets/35653876/cec249ad-79db-4c57-9128-ecbd39be53a2)

**Comment by Patil2099** [comment]
@Jackrekirby

**Comment by Jackrekirby** [comment]
This issue has been fixed in commit:
https://github.com/Jackrekirby/minecraft-ca-ts/commit/5dc95ea92f84ab7759fff054447131ec9eb96ea2

The canvas was not re-rendering on world clear/load when the tick set was set to zero.
